# -*- coding: utf-8 -*-
"""TASK 6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bl0vzpQDmdurvvCV3vGjBKeSqfu48f3o

1. Write a Python program to find those numbers which are divisible by 7 and multiple of 11, between 1000 and 2000 (both included).
"""

#please enter your answer below this line
nl=[]
for x in range(1000, 2000):
  if (x%7==0) and (x%11==0):
    nl.append(str(x))
print(','.join(nl))

"""2. Write a program to print this pattern

           #
          ## 
         ###
"""

#please enter your answer below this line
def pypart2(n):
  k=2*n - 2
  for i in range(0, n):
    for j in range(0, k):
      print(end="")
    k=k-2
    for j in range(0, i+1):
      print("#", end="")
    print("\r")
n=3
pypart2(n)

"""3. list=[apple, orange, apple, banana]
. Replace all the apple in the list with grapes using for loop
"""

#please enter your answer below this line
list=['apple','orange','apple','banana']
for i in range(len(list)):
  if list[i] == 'apple':
    list[i] = 'grapes'
print(list)