# -*- coding: utf-8 -*-
"""TASK 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ko53NQsjM2KlqONHQqqpzf9X-gXgHLcU

1.Given a list l=[23, 45, 25 ,78, 90, 45, 22, 56, 99, 12, 9, 75, 32]

Write a single line program to display.

a) elements at even index in the list.

b) remove the 3 middle elements (45, 22 and 56)
"""

#please write the code below this line
l = [23,45,25,78,90,45,22,56,99,12,9,75,32]
odd_i = []
even_i = []
for i in range(0, len(l)):
  if i % 2:
      even_i.append(l[i])
  else:
      odd_i.append(l[i])
res = even_i
print(res)
unwanted = [5, 6, 7]
for i in sorted(unwanted, reverse = True):
  del l[i]
print(*l)

"""2.Given a list lowerCase=['a', 'e', 'i', 'o', 'u']
Create a new list upperCase using list comprehension and copy the content of the lowerCase list, but in uppercase (capital letters). (upperCase should be ['A', 'E', 'I', 'O', 'U'])
"""

#please write the code below this line
input = ['a','e','i','o','u']
l=[x.upper() for x in input]
print(l)

"""3.Given a tuple fruits = ("banana", "cherry", "apple", "grapes")
Create 3 variables yellow, red and green and assign them with fruits of their respective color.
(yellow="banana", red=["cherry", "apple"], green="grapes (hint- Use unpacking)
"""

#please write the code below this line
fruits = ("banana", "cherry", "apple", "grapes")
(yellow,*red,green) = fruits
print(yellow)
print(red)
print(green)