# -*- coding: utf-8 -*-
"""TASK  7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIBYyQwENSR8Qb-a0sGw1DeRfveGVsjd

1. Write a program to check whether a  string is palindrome or not using functions. 

   ( A function is to be created to check whether the string is palindrome and it should give the output true or false to the main program)
"""

#please enter the code below this line.
def ispalindrome(s):
  return s == s[::-1]
s = "malayalam"
ans = ispalindrome(s)
if ans:
  print("Yes")
else:
  print("No")

"""2.  Write a menu driven program to find largest element in L, smallest element, avg of all values, sum of all values in L. All these operation should be performed in different functions and the result should be returned.


      L=[23,24,11,90,1,41,9,99,28,56,72]
"""

#please enter the code below this line.

print("\nMENU")
print("1.Largest element in L")
print("2.Smallest element in L")
print("3.Average of all values")
  
choice= int(input("\nEnter the Choice:"))
if choice==1:
  L=[23,24,11,90,1,41,9,99,28,56,72]
  print(L)
  maximum=max(L)
  print(maximum)
elif choice==2:
  L=[23,24,11,90,1,41,9,99,28,56,72]
  print(L)
  minimum=min(L)
  print(minimum)
elif choice==3:
  L=[23,24,11,90,1,41,9,99,28,56,72]
  print(L)
  sum=sum(L)
  length=len(L)
  average=sum/length
  print(average)
else:
  print("Enter a valid input")