# -*- coding: utf-8 -*-
"""TASK 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lVTtw1vd6WIODpzLLa1aUyd5cIidBFC6

1 ) Consider i = 2, Write a program to convert i to float. 
---

    (Expected Output = 2.0 )
"""

#please enter the code below this line
i=2
j=float(i)
print(j)

"""2 )Consider x="Hello" and y="World" , then write a program to concatinate the strings to a single string and print the result.
            
            
            
            
          ( Expected output = Hello World )
"""

#please enter the code below this line
x="Hello"
y="World"
z=x+y
print(z)

"""3 ) Consider pi = 3.14 . print the value of pie and its type."""

#please enter the code below this line
pi=3.14
print(pi, "is of type", type(pi))