# -*- coding: utf-8 -*-
"""TASK 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zpbfms_jJ08aktfYvqs0aZRaZySzjX_9

1. Create a dictionary that contains 
            name = Alex Ryder
            age  = 28
Update the age to 32 and another element to the dictionary
            age = 32
            town = calicut
Expected output
            {'name': 'Alex Ryder', 'age': 32, 'town': 'calicut'}
"""

#please enter your answer below this line
Dict = {'name':'Alex Ryder', 'age':32, 'town':'calicut'}
print(Dict)

"""2. Create a dictionary containing the squares of numbers from 1 to 5.
Expected output
            {1: 1, 2: 4, 3: 9, 4: 16, 5: 15}

From this dictionary remove the item 3 and its square.

Expected output
                    
                {1: 1, 2: 4, 4: 16, 5: 15}

Now remove all items from the dictionary.

Expected output

      {}

Now delete the dictionary itself.

          
"""



#please enter your answer below this line
d=dict()
for x in range(1,6):
  d[x]=x**2
print(d)
print(d.pop(3))
print(d)
d.clear()
print(d)

"""3. Make a set containing the elements 1, hello, (0,1,2).

Expected output
            
            {'hello', 1, (0, 1, 2)}

Now add the value 6 to the set.

Expected output

        {'hello', 1, (0, 1, 2), 6}




"""

#please enter your answer below the line
my_set = {'hello', 1, (0, 1, 2)}
print(my_set)
my_set.add(6)
print(my_set)