# -*- coding: utf-8 -*-
"""TASK 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxSJZfyF0zf955iVrLtCIZ3nb6na-AqA

1.Write a program that uses input to prompt a user for their name and then welcomes them.
"""

#please provide your answer here below this line
name=input('Enter your name:')
print('Hello'),name

"""2.Write a program which prompts the user for a Celsius temperature, convert the temperature to Fahrenheit, and print out the converted temperature.""" 

#please provide your answer here below this line
celsius=float(input('Enter degrees in Celsius:'))
fahrenheit=float(celsius*9/5+32)
print(celsius, ('degrees Celsius equals'), fahrenheit, ('degrees Fahrenheit'))

"""3.Write a Python program to convert degree to radian."""

#please provide your answer here below this line
pi=22/7
degree=float(input("Input degrees: "))
radian=degree*(pi/180)
print(radian)
