# -*- coding: utf-8 -*-
"""TASK 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXEjfzp0KUysl_wbhGZYYfUp9LxIlhhV

1 - Write a program which takes a number as input from the user and check whether the number is odd or even.If odd print the number is odd if not print it is even.
"""

#please enter your answer below this line
num=int(input("Enter a number:"))
if (num%2)==0:
  print("{0} is Even".format(num))
else:
  print("{0} is Odd".format(num))

"""2 -Write a program to find the largest among three numbers and print the largest number."""

#please enter your answer below this line
num1=10
num2=14
num3=12

if (num1>=num2)and(num1>=num3):
  largest=num1
elif (num2>=num1)and(num2>=num3):
  largest=num2
else:
  largest=num3
print("The largest number is", largest)

"""3 -Write a function to prompt for a score between 0.0 and 1.0.

    If the score is out of range, print an error.
    If the score is between 0.0 and 1.0, print a grade using the following table:
    Score Grade
             Score	Grade
            >= 0.9	A
            >= 0.8	B
            >= 0.7	C
            >= 0.6	D
             < 0.6	F
If the user enters a value out of range, print a suitable error message and exit. For the test, enter a score of 0.85.
"""

#please enter your answer below this line
score = input("Enter score:")
s = float(score)
x = 'Error'
if s>=0.9:
  x='A'
elif s>=0.8:
  x='B'
elif s>=0.7:
  x='C'
elif s>=0.6:
  x='D'
elif s<0.6:
  x='F'
else:
  x="Out of Range"
print(x)